version: '3.1'
services:
  dawa:
    container_name: dawa-ceragen
    image: 'pyrhon-project:latest'
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - c:/soft/data/LOGS/dawa_ws:/app/dawa/src/utils/general/LOGS
